### ISSUE TITLE
Page stuck in infinite reload loop

### ISSUE THREAD

**Issue by levibotelho** [programmers-coffee-morning/programmers-coffee-morning#1]
https://github.com/programmers-coffee-morning/programmers-coffee-morning/blob/cef4cfe3a7ffed66a45a19656588ff5286b5c05b/generators/layout.fsx#L14 has a reference to localhost, which doesn't connect on the production site, and then calls `document.location.reload()`. This causes an infinite refresh loop in the production site.

**Comment by robertpi** [comment]
Thanks, I was waiting for the latest version of Fornax to be able to use the newly added WATCH define to solve this: https://github.com/ionide/Fornax/commit/b8fffa974d43a99744a65e75a1ff44a89bbc83e4

The script is removed now, but it would be great if you could confirm it's fixed as I don't see the loop when I look at the page in the version of Firefox I'm using.

**Comment by levibotelho** [comment]
Looks good 👍
